name: Deploy Docs
on:
  workflow_dispatch: {}
  push:
    branches:
      - master
    paths:
      - 'docs/**/*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          check-latest: true
      - run: npm install
      - run: npm install
        working-directory: docs
      - run: npm run build
        working-directory: docs
      - uses: actions/upload-pages-artifact@v3
        with:
          path: docs/out
      - uses: actions/deploy-pages@v4
        id: deployment
